export const ASSETS: string[] = [
  // shared (frame.png preloaded in index.ts before loading screen)
  'rbutton/Forward.png',
  'rbutton/Forward_Hover.png',
  'rbutton/Forward_Clicked.png',
  'lbutton/Back.png',
  'lbutton/Back_Hover.png',
  'lbutton/Back_Clicked.png',

  // audio
  'Music/girlstory_loop1.mp3',
  'Music/aamistory_loop2.mp3',

  // intro / firefly cursor (reused across all scenes)
  // Intro.jpg, firefly-1..5, LoadingCircle, LoadingText preloaded in index.ts
  'intro_scene/intro_text.png',
  'intro_scene/rev_firefly/RevFirefly-1.png',
  'intro_scene/rev_firefly/RevFirefly-2.png',
  'intro_scene/rev_firefly/RevFirefly-3.png',
  'intro_scene/rev_firefly/RevFirefly-4.png',
  'intro_scene/rev_firefly/RevFirefly-5.png',

  // title screen
  'title_screen/BG.png',
  'title_screen/Front.png',
  'title_screen/Leaves.png',
  'title_screen/heart/1.png',
  'title_screen/heart/2.png',
  'title_screen/heart/3.png',
  'title_screen/heart/4.png',

  // scene one
  'scene_one/Background.png',
  'scene_one/House_Grass.png',
  'scene_one/wheat.png',
  'scene_one/Aami.png',
  'scene_one/jackal_new.png',
  'scene_one/Text1.png',
  'scene_one/Text2.png',
  'scene_one/Text3.png',
  'scene_one/rain/rain-1.png',
  'scene_one/rain/rain-2.png',
  'scene_one/rain/rain-3.png',

  // scene two (also reused by scene 15)
  'scene_two/Background.png',
  'scene_two/Aami.png',
  'scene_two/Grass.png',
  'scene_two/Jackal.png',
  'scene_two/Pillars.png',
  'scene_two/Text_1.png',
  'scene_two/Text2.png',

  // scene three
  'scene_three/Background.png',
  'scene_three/Aami.png',
  'scene_three/BG_Trees_new.png',
  'scene_three/find.png',
  'scene_three/FireGlow.png',
  'scene_three/House1Closed.png',
  'scene_three/House1Open.png',
  'scene_three/House2Closed.png',
  'scene_three/House2Open.png',
  'scene_three/House3Closed.png',
  'scene_three/House3Open.png',
  'scene_three/Text 1.png',
  'scene_three/candle/CandleFire-1.png',
  'scene_three/candle/CandleFire-2.png',
  'scene_three/candle/CandleFire-3.png',
  'scene_three/candle/CandleFire.png',
  'scene_three/new/Glow 1.png',
  'scene_three/new/Glow 2.png',
  'scene_three/new/Text 1.png',
  'scene_three/new/Text 2 .png',

  // scene four
  'scene_four/Background.png',
  'scene_four/DRAG INGRIDIENTS INTO THE POT.png',
  'scene_four/Meal.png',
  'scene_four/pot.png',
  'scene_four/Spice.png',
  'scene_four/Coconut Milk.png',
  'scene_four/Dry Fruits.png',
  'scene_four/Rice.png',
  'scene_four/Honey.png',
  'scene_four/Text 1.png',
  'scene_four/Text 2.png',
  'scene_four/fire/KitchenFire-1.png',
  'scene_four/fire/KitchenFire-2.png',
  'scene_four/fire/KitchenFire-3.png',
  'scene_four/smoke/KitchenSmoke-1.png',
  'scene_four/smoke/KitchenSmoke-2.png',
  'scene_four/smoke/KitchenSmoke-3.png',
  'scene_four/smoke/KitchenSmoke-4.png',

  // scene five
  'scene_five/Background.png',
  'scene_five/Aami and Plate.png',
  'scene_five/CLICK AGAIN!.png',
  'scene_five/CLICK ON THE JACKAL TO CALL HIM.png',
  'scene_five/Grass.png',
  'scene_five/Jackal1.png',
  'scene_five/Jackal2.png',
  'scene_five/Jackal3.png',
  'scene_five/ojackal.png',
  'scene_five/Text 1.png',
  'scene_five/Text 2.png',
  'scene_five/Text 3.png',

  // scene six
  'scene_six/Background.png',
  'scene_six/Glow.png',
  'scene_six/Overlay with Text 1.png',
  'scene_six/Text 1.png',
  'scene_six/Text2.png',
  'scene_six/soul/Scene6Soul1.png',
  'scene_six/soul/Scene6Soul2.png',
  'scene_six/soul/Scene6Soul3.png',
  'scene_six/soul/Scene6Soul4.png',

  // scene seven
  'scene_seven/Background.png',
  'scene_seven/clearbush2.png',
  'scene_seven/Grass.png',
  'scene_seven/Layer 13.png',
  'scene_seven/Layer1Aami.png',
  'scene_seven/Layer2Aami.png',
  'scene_seven/Layer3Aami.png',
  'scene_seven/LeftBush.png',
  'scene_seven/LeftBush 2.png',
  'scene_seven/LeftTree.png',
  'scene_seven/LeftTree 2.png',
  'scene_seven/MidTree.png',
  'scene_seven/RightBush.png',
  'scene_seven/RightBush 2.png',
  'scene_seven/RightTree.png',
  'scene_seven/RightTree 2.png',
  'scene_seven/Text 1.png',
  'scene_seven/Text 2.png',
  'scene_seven/Text 3.png',

  // scene eight
  'scene_eight/Background.png',
  'scene_eight/BG.png',
  'scene_eight/Aami.png',
  'scene_eight/Glow.png',
  'scene_eight/Glow 2.png',
  'scene_eight/Tiger.png',
  'scene_eight/Text 1.png',
  'scene_eight/Text 2.png',
  'scene_eight/Text 3.png',
  'scene_eight/Text 4.png',
  'scene_eight/bg_shift/Scene8BGShift1.png',
  'scene_eight/bg_shift/Scene8BGShift2.png',
  'scene_eight/bg_shift/Scene8BGShift3.png',
  'scene_eight/bg_shift/Scene8BGShift4.png',

  // scene 9
  'scene_9/Background.png',
  'scene_9/Aami.png',
  'scene_9/hover.png',
  'scene_9/Kalmegh.png',
  'scene_9/Kalmegh Hovered.png',
  'scene_9/Nona tenga.png',
  'scene_9/Noga tenga Hovered.png',
  'scene_9/Titaphul.png',
  'scene_9/Titaphul hovered.png',
  'scene_9/Strong.png',
  'scene_9/Weak.png',
  'scene_9/Text 1.png',
  'scene_9/Text 2.png',

  // scene 10
  'scene_10/Layer 26.png',
  'scene_10/Water.png',
  'scene_10/Text 1.png',
  'scene_10/waves/Scene10Waves1.png',
  'scene_10/waves/Scene10Waves2.png',
  'scene_10/waves/Scene10Waves3.png',
  'scene_10/waves/Scene10Waves4.png',

  // scene 11
  'scene_11/Background.png',
  'scene_11/Text1.png',
  'scene_11/Text2.png',
  'scene_11/Text3.png',
  'scene_11/glowstring/Scene11GlowString1.png',
  'scene_11/glowstring/Scene11GlowString2.png',
  'scene_11/glowstring/Scene11GlowString3.png',
  'scene_11/glowstring/Scene11GlowString4.png',
  'scene_11/glowstring/Scene11GlowString5.png',
  'scene_11/glowstring/Scene11GlowString6.png',

  // scene 12
  'scene_12/Background.png',
  'scene_12/Aami.png',
  'scene_12/Lake.png',
  'scene_12/Trees.png',
  'scene_12/Goddess.png',
  'scene_12/Clear Water (hidden).png',
  'scene_12/click.png',
  'scene_12/Text1.png',
  'scene_12/Text2.png',
  'scene_12/Text3.png',
  'scene_12/Text4.png',

  // scene 13
  'scene_13/Background.png',
  'scene_13/Malati.png',
  'scene_13/Text1.png',
  'scene_13/Text2.png',
  'scene_13/glow/Scene13GoddessGlow1.png',
  'scene_13/glow/Scene13GoddessGlow2.png',
  'scene_13/glow/Scene13GoddessGlow3.png',
  'scene_13/glow/Scene13GoddessGlow4.png',

  // scene 14
  'scene_14/Background.png',
  'scene_14/Aami.png',
  'scene_14/Grass.png',
  'scene_14/LeftTree.png',
  'scene_14/MidTree.png',
  'scene_14/RightTree.png',
  'scene_14/click.png',
  'scene_14/Scene14LeftFlower1.png',
  'scene_14/Scene14LeftFlower2.png',
  'scene_14/Scene14MidFlower1.png',
  'scene_14/Scene14MidFlower2.png',
  'scene_14/Scene14RightFlower1.png',
  'scene_14/Scene14RightFlower2.png',
  'scene_14/Scene14Stars1.png',
  'scene_14/Scene14Stars2.png',
  'scene_14/Text1.png',
  'scene_14/Text2.png',
  'scene_14/Text3.png',

  // scene 15 (uses scene_two backgrounds + own text)
  'scene_15/Text 1.png',
  'scene_15/Text 2.png',

  // scene 16
  'scene_16/Background.png',
  'scene_16/Aami & Jackal.png',
  'scene_16/Wheat.png',
  'scene_16/Dialogue.png',
  'scene_16/Text1.png',
  'scene_16/Text2.png',

  // scene 17
  'scene_17/Background.png',
  'scene_17/Aami.png',
  'scene_17/Ground.png',
  'scene_17/Jackal1.png',
  'scene_17/Jackal2.png',
  'scene_17/Layer 6.png',
  'scene_17/Text1.png',
  'scene_17/Text2.png',
  'scene_17/Text3.png',

  // end
  'end/TheEnd1.png',
  'end/TheEnd2.png',
  'end/TheEnd3.png',

  // credits
  'credits/Background.png',
  'credits/Text2 copy 3.png',
  'credits/Text2 copy 4.png',
  'credits/Text2 copy 5.png',
];
